### ISSUE TITLE
Some of your languages images seem broken.

### ISSUE THREAD

**Issue by NS007-dev** [frankiefab100/frankiefab100#1]
@frankiefab100 , the php and photoshop images are not working, and I tried to fix it, but it didn't seem to work: 
![image](https://user-images.githubusercontent.com/70807500/130198841-b81d4f86-cd5e-4edd-9f06-f847c57a6dea.png)
thank you.

**Comment by frankiefab100** [comment]
Yeah, the link to the source is broken
